spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8761
eureka:
  client:
    instance-info-replication-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-auto-expiration-in-seconds: 5
logging:
  level:
    "com.netflix.eureka.registry.AbstractInstanceRegistry": warn